name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the latest code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, mysql, zip, curl
    
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        exclude: |
          **/.git*
          **/.git/**/
          **/node_modules/**
          **/.diagram.json
          **/.env